## Основные цвета
foreground            #ffffef
background            #000000
selection_background  #c49aff
selection_foreground  #000000
cursor                #40fbff
cursor_text_color     #000000

## Таблица из 16 цветов (ANSI)
## Black
color0                #000000
color8                #2a2a2a

## Red
color1                #ff4c4c
color9                #ff4c4c

## Green
color2                #66ff6e
color10               #66ff6e

## Yellow
color3                #fffc36
color11               #fffc36

## Blue
color4                #c49aff
color12               #c49aff

## Magenta
color5                #c49aff
color13               #c49aff

## Cyan
color6                #40fbff
color14               #40fbff

## White
color7                #ffffef
color15               #ffffef
